spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8961

eureka:
  instance:
    hostname: localhost   #eureka服务的地址
  client:   #服务端
    registerWithEureka: false   #不改成false那么就会认为你是个客户端
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/